language: java
sudo: false
jdk:
  - openjdk7
  - oraclejdk7

install:
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-105.0.0-linux-x86_64.tar.gz
  - tar -xf google-cloud-sdk-105.0.0-linux-x86_64.tar.gz
  - yes | ./google-cloud-sdk/install.sh
  - yes | ./google-cloud-sdk/bin/gcloud components install app-engine-java

before_deploy:
  - ./google-cloud-sdk/bin/gcloud auth activate-service-account "$SERVICE_EMAIL" --key-file mixxy-secret.json --project "$PROJECT_ID"
  - mvn appengine:update

deploy:
  provider: gae
  keyfile: mixxy-secret.json
  project: mixxy-1249
  config: src/main/webapp/WEB-INF/appengine-web.xml
  on:
    jdk: oraclejdk7

cache:
  directories:
    - "$HOME/.m2"

before_install:
  - openssl aes-256-cbc -K $encrypted_acb534f64c3b_key -iv $encrypted_acb534f64c3b_iv -in secrets.tar.gz.enc -out secrets.tar.gz -d
  - tar -axf secrets.tar.gz 2> /dev/null
  - gpg --import "$MIXXY_PRIVATE_KEY_NAME"
  - git clone https://github.com/AGWA/git-crypt ~/git-crypt
  - cd ~/git-crypt
  - make
  - cd -
  - ~/git-crypt/git-crypt unlock
  # Temporary, until git-crypt package is whitelisted
